"""
导出预训练权重为 C 头文件 (export_weights.py)
============================================
河海大学智泽实验室 2026 招新考核
张杨亦航 (2524030231)

将 e1_1d_weights.npz / e1_2d_weights.npz 导出为 test.cpp 可直接
#include 的 C 数组头文件, 用于 C++ 版本的神经网络推理。

用法:
  python export_weights.py
"""
import numpy as np
import os


def fmt_float(x: float) -> str:
    return f'{x:.15e}'


def export_npz(npz_path: str, h_path: str, suffix: str):
    """将单个 .npz 文件导出为 C 头文件"""
    d = np.load(npz_path)
    key_order = sorted(d.keys())

    total_params = sum(d[k].size for k in key_order)

    with open(h_path, 'w', encoding='utf-8') as f:
        f.write(f'// Auto-generated from {os.path.basename(npz_path)}\n')
        f.write(f'// Total parameters: {total_params}\n')
        f.write(f'// Generated by export_weights.py\n\n')

        for key in key_order:
            arr = d[key].astype(np.float64)
            f.write(f'// {key}: shape={arr.shape}\n')
            flat = arr.flatten()
            f.write(f'static const double {key}_{suffix}[] = {{\n')
            for i, val in enumerate(flat):
                f.write(f'  {fmt_float(val)}')
                if i < len(flat) - 1:
                    f.write(',')
                f.write('\n')
            f.write('};\n\n')

    print(f'  {h_path}: {total_params} params, {len(key_order)} arrays')


if __name__ == '__main__':
    base = os.path.dirname(os.path.abspath(__file__))

    export_npz(os.path.join(base, 'e1_1d_weights.npz'),
               os.path.join(base, 'e1_1d_weights.h'), '1d')

    export_npz(os.path.join(base, 'e1_2d_weights.npz'),
               os.path.join(base, 'e1_2d_weights.h'), '2d')

    print('\nDone! Now compile test.cpp with:')
    print('  cl /EHsc /std:c++20 /utf-8 /Fe:e1_test.exe test.cpp')
